import type {
  AdMode,
  Ban,
  Campaign,
  ClaimStatus,
  DepositOrder,
  LeaderEntry,
  NotificationItem,
  NotificationType,
  Platform,
  PremiumPlan,
  Referral,
  ReportEntry,
  Submission,
  Task,
  TaskAction,
  Tier,
  ToastMsg,
  Transaction,
  Trend,
  UserProfile,
  WithdrawalRequest,
} from "./types";
import { currentUserId, isSupabaseReady } from "./supabase";

export { PLATFORM_META } from "./platform-meta";

// Re-export shared types so existing imports of `type { Platform, Task } from "@/lib/mock-data"` keep working.
export type {
  AdMode,
  Ban,
  ClaimStatus,
  DepositOrder,
  LeaderEntry,
  NotificationItem,
  NotificationType,
  Platform,
  PremiumPlan,
  Referral,
  ReportEntry,
  Submission,
  Task,
  TaskAction,
  Tier,
  ToastMsg,
  Transaction,
  Trend,
  UserProfile,
  WithdrawalRequest,
} from "./types";

export const PLATFORMS: Platform[] = [
  "Instagram",
  "Telegram",
  "YouTube",
  "Twitter",
  "TikTok",
  "Play Store",
  "App Store",
  "Browser",
];

export const TASK_ACTIONS = [
  "Follow",
  "Like",
  "Subscribe",
  "Retweet",
  "Join",
  "View",
  "Comment",
  "Referral",
  "Install",
  "Download",
  "Rate",
  "Visit",
] as const;

/** User registry — anyone can follow anyone, report, and be ranked. */
export const USERS: Record<string, UserProfile> = {
  luxewears: {
    handle: "luxewears",
    tg: "luxewears",
    name: "Luxe Wears",
    tier: "Platinum",
    isPremium: true,
    rating: 4.9,
    ratingCount: 412,
    successRate: 96,
    followers: 128400,
    following: 512,
    tasksDone: 48,
  },
  cryptoalpha: {
    handle: "cryptoalpha",
    tg: "CryptoAlphaVIP",
    name: "CryptoAlpha",
    tier: "Platinum",
    isPremium: true,
    rating: 4.8,
    ratingCount: 356,
    successRate: 94,
    followers: 96400,
    following: 84,
    tasksDone: 37,
  },
  codemaster: {
    handle: "codemaster",
    tg: "CodeMasterPro",
    name: "CodeMaster",
    tier: "Gold",
    isPremium: true,
    rating: 4.7,
    ratingCount: 289,
    successRate: 92,
    followers: 58300,
    following: 201,
    tasksDone: 29,
  },
  promopulse: {
    handle: "promopulse",
    tg: "promopulse",
    name: "PromoPulse",
    tier: "Gold",
    isPremium: false,
    rating: 4.6,
    ratingCount: 210,
    successRate: 95,
    followers: 41200,
    following: 128,
    tasksDone: 22,
  },
  mira: {
    handle: "mira",
    tg: "dancewithmira",
    name: "Mira",
    tier: "Silver",
    isPremium: false,
    rating: 4.5,
    ratingCount: 96,
    successRate: 90,
    followers: 12800,
    following: 350,
    tasksDone: 18,
  },
  web3wave: {
    handle: "web3wave",
    tg: "web3wave",
    name: "Web3Wave",
    tier: "Gold",
    isPremium: true,
    rating: 4.8,
    ratingCount: 178,
    successRate: 93,
    followers: 44600,
    following: 76,
    tasksDone: 26,
  },
  nftdrops: {
    handle: "nftdrops",
    tg: "NFTDropsHub",
    name: "NFTDropsHub",
    tier: "Gold",
    isPremium: true,
    rating: 4.4,
    ratingCount: 142,
    successRate: 89,
    followers: 39800,
    following: 95,
    tasksDone: 31,
  },
  streetdaily: {
    handle: "streetdaily",
    tg: "streetdaily",
    name: "Street Daily",
    tier: "Gold",
    isPremium: false,
    rating: 4.3,
    ratingCount: 118,
    successRate: 88,
    followers: 22400,
    following: 430,
    tasksDone: 15,
  },
  brandx: {
    handle: "brandx",
    tg: "brandx",
    name: "Brand X",
    tier: "Silver",
    isPremium: false,
    rating: 4.2,
    ratingCount: 87,
    successRate: 86,
    followers: 9600,
    following: 64,
    tasksDone: 11,
  },
  ariachen: {
    handle: "ariachen",
    tg: "aria_chen",
    name: "Aria Chen",
    tier: "Platinum",
    isPremium: true,
    rating: 4.9,
    ratingCount: 302,
    successRate: 99,
    followers: 24800,
    following: 812,
    tasksDone: 214,
  },
  diegor: {
    handle: "diegor",
    tg: "diego_rivera",
    name: "Diego Rivera",
    tier: "Platinum",
    isPremium: false,
    rating: 4.8,
    ratingCount: 254,
    successRate: 98,
    followers: 18300,
    following: 640,
    tasksDone: 198,
  },
  meitanaka: {
    handle: "meitanaka",
    tg: "mei_tanaka",
    name: "Mei Tanaka",
    tier: "Gold",
    isPremium: true,
    rating: 4.7,
    ratingCount: 198,
    successRate: 97,
    followers: 12900,
    following: 505,
    tasksDone: 176,
  },
  jordanray: {
    handle: "jordanray",
    tg: "jordan_ray",
    name: "Jordan Ray",
    tier: "Gold",
    isPremium: false,
    rating: 4.6,
    ratingCount: 171,
    successRate: 96,
    followers: 10900,
    following: 388,
    tasksDone: 162,
  },
  sarakhan: {
    handle: "sarakhan",
    tg: "sara_khan",
    name: "Sara Khan",
    tier: "Gold",
    isPremium: true,
    rating: 4.6,
    ratingCount: 156,
    successRate: 95,
    followers: 9800,
    following: 422,
    tasksDone: 149,
  },
  pabloo: {
    handle: "pabloo",
    tg: "pablo_ortiz",
    name: "Pablo Ortiz",
    tier: "Gold",
    isPremium: false,
    rating: 4.5,
    ratingCount: 134,
    successRate: 94,
    followers: 8700,
    following: 299,
    tasksDone: 141,
  },
  linwu: {
    handle: "linwu",
    tg: "lin_wu",
    name: "Lin Wu",
    tier: "Silver",
    isPremium: false,
    rating: 4.5,
    ratingCount: 112,
    successRate: 93,
    followers: 7600,
    following: 356,
    tasksDone: 128,
  },
  evemu: {
    handle: "evemu",
    tg: "eve_muller",
    name: "Eve Müller",
    tier: "Silver",
    isPremium: false,
    rating: 4.4,
    ratingCount: 98,
    successRate: 92,
    followers: 6400,
    following: 274,
    tasksDone: 116,
  },
  kenadams: {
    handle: "kenadams",
    tg: "ken_adams",
    name: "Ken Adams",
    tier: "Silver",
    isPremium: false,
    rating: 4.3,
    ratingCount: 76,
    successRate: 91,
    followers: 5400,
    following: 201,
    tasksDone: 104,
  },
  you: {
    handle: "you",
    tg: "",
    name: "You",
    tier: "Gold",
    isPremium: false,
    rating: 4.7,
    ratingCount: 64,
    successRate: 94,
    followers: 348,
    following: 12,
    tasksDone: 96,
    isYou: true,
  },
};

// ---------------------------------------------------------------------------
// Database-backed profiles
//
// When Supabase is configured, getUser() MUST NOT return demo USERS data — the
// profile registry is hydrated from the `profiles` table and any unknown
// handle resolves to a neutral (zeroed) profile instead of fake numbers.
// ---------------------------------------------------------------------------

const profileRegistry = new Map<string, UserProfile>();

/** Replace the profile registry with rows loaded from Supabase (on hydrate). */
export function registerProfiles(profiles: UserProfile[]): void {
  profileRegistry.clear();
  profiles.forEach((p) => profileRegistry.set(p.handle, p));
}

function neutralProfile(handle: string): UserProfile {
  return {
    handle,
    tg: "",
    name: handle.charAt(0).toUpperCase() + handle.slice(1),
    tier: "Silver",
    isPremium: false,
    rating: 0,
    ratingCount: 0,
    successRate: 0,
    fiveStarGives: 0,
    fourStarGives: 0,
    followers: 0,
    following: 0,
    tasksDone: 0,
  };
}

export function getUser(handle: string): UserProfile {
  // In DB mode the profile row is keyed by currentUserId() ("tg-<id>" inside
  // Telegram), while pages pass "you" for the current user — resolve it so the
  // registry hit actually happens.
  const key = isSupabaseReady() && handle === "you" ? currentUserId() : handle;
  const db = profileRegistry.get(key);
  if (db) return db;
  // DB mode: never invent fake profiles/numbers.
  if (isSupabaseReady()) return neutralProfile(handle);
  return USERS[handle] ?? neutralProfile(handle);
}

export const PREMIUM_PLANS: PremiumPlan[] = [
  {
    id: "week",
    label: "1 Week",
    price: 0.79,
    days: 7,
    postsPerDay: 4,
    leadsPerPostPerDay: 50,
    perks: ["Verified blue tick", "4 posts / day", "50 leads per post / day", "Ban threshold 10+/hour (72h)", "Priority claim approval"],
  },
  {
    id: "month",
    label: "1 Month",
    price: 1.99,
    days: 30,
    postsPerDay: 10,
    leadsPerPostPerDay: 100,
    perks: ["Verified blue tick", "10 posts / day", "100 leads per post / day", "Ban threshold 10+/hour (72h)", "Priority claim approval", "Free ad boost (weekly)"],
  },
  {
    id: "halfyear",
    label: "3 Months",
    price: 4.19,
    days: 90,
    postsPerDay: 100,
    leadsPerPostPerDay: 100,
    perks: ["Verified blue tick", "100 posts / day", "100 leads per post / day", "Ban threshold 10+/hour (72h)", "Priority claim approval", "Free ad boost (weekly)", "Best value · save 30% vs monthly"],
  },
];

/** Popular search tags offered on the publish form & feed editor. */
export const SUGGESTED_TAGS = [
  "crypto",
  "fashion",
  "gaming",
  "fitness",
  "food",
  "tech",
  "music",
  "nft",
  "travel",
  "finance",
  "beauty",
  "sports",
];

/** Suggested interest tags for the "my feed" matcher. */
export const INTEREST_TAGS = [
  "crypto",
  "fashion",
  "gaming",
  "fitness",
  "food",
  "tech",
  "music",
  "nft",
  "travel",
  "finance",
  "beauty",
  "sports",
  "apps",
  "trading",
];

export const TASKS: Task[] = [
  {
    id: "t1",
    postId: "PP-7K2XQ9",
    tags: ["fashion", "streetwear", "style"],
    platform: "Instagram",
    action: "Follow",
    title: "Follow @luxewears for daily drops",
    target: "@luxewears",
    reward: 50,
    completions: 142,
    limit: 200,
    minutesAgo: 4,
    poster: "Luxe Wears",
    posterHandle: "luxewears",
    verified: true,
    rating: 4.9,
    ratingCount: 412,
    successRate: 96,
    mode: "paid",
    likes: 231,
  },
  {
    id: "t2",
    postId: "PP-9M4TZ1",
    tags: ["crypto", "trading", "signals"],
    platform: "Telegram",
    action: "Join",
    title: "Join CryptoAlpha Signals Channel",
    target: "@CryptoAlphaVIP",
    reward: 80,
    completions: 380,
    limit: 500,
    minutesAgo: 12,
    poster: "CryptoAlpha",
    posterHandle: "cryptoalpha",
    verified: true,
    rating: 4.8,
    ratingCount: 356,
    successRate: 94,
    mode: "paid",
    likes: 198,
  },
  {
    id: "t3",
    postId: "PP-2B8RW5",
    tags: ["tech", "coding", "web3"],
    platform: "YouTube",
    action: "Subscribe",
    title: "Subscribe to CodeMaster — Web3 tutorials",
    target: "@CodeMasterPro",
    reward: 120,
    completions: 58,
    limit: 300,
    minutesAgo: 22,
    poster: "CodeMaster",
    posterHandle: "codemaster",
    verified: true,
    rating: 4.7,
    ratingCount: 289,
    successRate: 92,
    mode: "paid",
    likes: 156,
  },
  {
    id: "t4",
    postId: "PP-5H3NP6",
    tags: ["marketing", "launch", "promo"],
    platform: "Twitter",
    action: "Retweet",
    title: "Retweet our launch announcement",
    target: "@PromoPulse/status/1729",
    reward: 40,
    completions: 410,
    limit: 500,
    minutesAgo: 33,
    poster: "PromoPulse",
    posterHandle: "promopulse",
    verified: false,
    rating: 4.6,
    ratingCount: 210,
    successRate: 95,
    mode: "paid",
    likes: 102,
  },
  {
    id: "t5",
    postId: "PP-8Q6VL2",
    tags: ["dance", "music", "entertainment"],
    platform: "TikTok",
    action: "Follow",
    title: "Follow @dancewithmira",
    target: "@dancewithmira",
    reward: 35,
    completions: 89,
    limit: 250,
    minutesAgo: 51,
    poster: "Mira",
    posterHandle: "mira",
    verified: false,
    rating: 4.5,
    ratingCount: 96,
    successRate: 90,
    mode: "paid",
    likes: 87,
  },
  {
    id: "t6",
    postId: "PP-3D1FJ7",
    tags: ["fashion", "products", "drops"],
    platform: "Instagram",
    action: "Like",
    title: "Like our latest product post",
    target: "/p/CxT9a2Lkx9P",
    reward: 25,
    completions: 1210,
    limit: 1500,
    minutesAgo: 64,
    poster: "Luxe Wears",
    posterHandle: "luxewears",
    verified: true,
    rating: 4.9,
    ratingCount: 412,
    successRate: 96,
    mode: "paid",
    likes: 301,
  },
  {
    id: "t7",
    postId: "PP-6S9CK4",
    tags: ["tech", "video", "launch"],
    platform: "YouTube",
    action: "Like",
    title: "Like the launch trailer video",
    target: "/watch?v=al9k2",
    reward: 15,
    completions: 1880,
    limit: 3000,
    minutesAgo: 95,
    poster: "PromoPulse",
    posterHandle: "promopulse",
    verified: false,
    rating: 4.6,
    ratingCount: 210,
    successRate: 95,
    mode: "paid",
    likes: 176,
  },
  {
    id: "t8",
    postId: "PP-4Y7XB3",
    tags: ["crypto", "nft", "alpha"],
    platform: "Twitter",
    action: "Follow",
    title: "Follow @Web3Wave for alpha",
    target: "@Web3Wave",
    reward: 60,
    completions: 215,
    limit: 300,
    minutesAgo: 110,
    poster: "Web3Wave",
    posterHandle: "web3wave",
    verified: true,
    rating: 4.8,
    ratingCount: 178,
    successRate: 93,
    mode: "paid",
    likes: 143,
  },
  {
    id: "t9",
    postId: "PP-1W5ZR8",
    tags: ["nft", "crypto", "community"],
    platform: "Telegram",
    action: "Join",
    title: "Join NFTDropsHub discussion",
    target: "@NFTDropsHub",
    reward: 70,
    completions: 199,
    limit: 400,
    minutesAgo: 140,
    poster: "NFTDropsHub",
    posterHandle: "nftdrops",
    verified: true,
    rating: 4.4,
    ratingCount: 142,
    successRate: 89,
    mode: "paid",
    likes: 118,
  },
  {
    id: "t10",
    postId: "PP-9N2GK5",
    tags: ["fashion", "streetwear", "urban"],
    platform: "Instagram",
    action: "Follow",
    title: "Follow @streetwear.daily",
    target: "@streetwear.daily",
    reward: 45,
    completions: 312,
    limit: 400,
    minutesAgo: 180,
    poster: "Street Daily",
    posterHandle: "streetdaily",
    verified: false,
    rating: 4.3,
    ratingCount: 118,
    successRate: 88,
    mode: "paid",
    likes: 92,
  },
  {
    id: "t11",
    postId: "PP-7R4LM1",
    tags: ["brand", "entertainment", "viral"],
    platform: "TikTok",
    action: "View",
    title: "Watch our newest viral clip",
    target: "/@brand/v/882",
    reward: 20,
    completions: 980,
    limit: 2000,
    minutesAgo: 220,
    poster: "Brand X",
    posterHandle: "brandx",
    verified: false,
    rating: 4.2,
    ratingCount: 87,
    successRate: 86,
    mode: "paid",
    likes: 64,
  },
  {
    id: "t12",
    postId: "PP-2T8PH6",
    tags: ["fashion", "engagement", "launch"],
    platform: "Instagram",
    action: "Comment",
    title: "Comment 'FIRE' on our launch post",
    target: "/p/CxT9a2Lkx9P",
    reward: 90,
    completions: 71,
    limit: 150,
    minutesAgo: 290,
    poster: "Luxe Wears",
    posterHandle: "luxewears",
    verified: true,
    rating: 4.9,
    ratingCount: 412,
    successRate: 96,
    mode: "paid",
    likes: 133,
  },
  {
    id: "t13",
    postId: "PP-6F3SD9",
    tags: ["crypto", "referral", "signals"],
    platform: "Telegram",
    action: "Referral",
    title: "Join CryptoAlpha & enter code CA7X (referral exchange)",
    target: "@CryptoAlphaVIP",
    reward: 0,
    completions: 44,
    limit: 300,
    minutesAgo: 8,
    poster: "CryptoAlpha",
    posterHandle: "cryptoalpha",
    verified: true,
    rating: 4.8,
    ratingCount: 356,
    successRate: 94,
    mode: "referral",
    likes: 128,
    instructions:
      "Join @CryptoAlphaVIP on Telegram, open your profile and enter referral code CA7X, then describe what you completed.",
  },
  {
    id: "t14",
    postId: "PP-5J9QW4",
    tags: ["apps", "finance", "install"],
    platform: "Play Store",
    action: "Install",
    title: "Install NovaPay — 5★ finance app",
    target: "https://play.google.com/store/apps/details?id=com.novapay.app",
    reward: 95,
    completions: 18,
    limit: 200,
    minutesAgo: 6,
    poster: "NovaPay",
    posterHandle: "novapay",
    verified: true,
    rating: 4.8,
    ratingCount: 141,
    successRate: 93,
    mode: "paid",
    likes: 74,
  },
  {
    id: "t15",
    postId: "PP-3C7RV2",
    tags: ["apps", "fitness", "rating"],
    platform: "App Store",
    action: "Rate",
    title: "Rate FitLife on the App Store (5★)",
    target: "https://apps.apple.com/app/id1234567890",
    reward: 85,
    completions: 9,
    limit: 150,
    minutesAgo: 18,
    poster: "FitLife",
    posterHandle: "fitlife",
    verified: true,
    rating: 4.7,
    ratingCount: 88,
    successRate: 91,
    mode: "paid",
    likes: 41,
  },
  {
    id: "t16",
    postId: "PP-8W1TN7",
    tags: ["tech", "beta", "signup"],
    platform: "Browser",
    action: "Visit",
    title: "Visit our landing page & sign up for the beta",
    target: "https://promopulse.gg/beta",
    reward: 55,
    completions: 27,
    limit: 400,
    minutesAgo: 35,
    poster: "PromoPulse",
    posterHandle: "promopulse",
    verified: false,
    rating: 4.6,
    ratingCount: 210,
    successRate: 95,
    mode: "paid",
    likes: 96,
  },
];

export const CAMPAIGNS: Campaign[] = [
  {
    id: "c0",
    title: "Your IG Followers Sprint",
    platform: "Instagram",
    action: "Follow",
    target: "@you",
    reward: 45,
    quantity: 120,
    budget: 5400,
    spent: 1350,
    status: "active",
    completions: 30,
    approvers: 4,
    createdDaysAgo: 1,
    poster: "You",
    posterHandle: "you",
    verified: false,
    rating: 4.7,
    ratingCount: 64,
    successRate: 94,
    mode: "paid",
  },
  {
    id: "c1",
    title: "Luxe Wears — IG Followers Sprint",
    platform: "Instagram",
    action: "Follow",
    target: "@luxewears",
    reward: 50,
    quantity: 500,
    budget: 30000,
    spent: 7100,
    status: "active",
    completions: 142,
    approvers: 11,
    createdDaysAgo: 2,
    poster: "Luxe Wears",
    posterHandle: "luxewears",
    verified: true,
    rating: 4.9,
    ratingCount: 412,
    successRate: 96,
    mode: "paid",
  },
  {
    id: "c2",
    title: "CryptoAlpha — VIP Channel Drive",
    platform: "Telegram",
    action: "Join",
    target: "@CryptoAlphaVIP",
    reward: 80,
    quantity: 1000,
    budget: 95000,
    spent: 30400,
    status: "active",
    completions: 380,
    approvers: 42,
    createdDaysAgo: 5,
    poster: "CryptoAlpha",
    posterHandle: "cryptoalpha",
    verified: true,
    rating: 4.8,
    ratingCount: 356,
    successRate: 94,
    mode: "paid",
  },
  {
    id: "c3",
    title: "CodeMaster — YouTube Subscribers",
    platform: "YouTube",
    action: "Subscribe",
    target: "@CodeMasterPro",
    reward: 120,
    quantity: 300,
    budget: 42000,
    spent: 6960,
    status: "active",
    completions: 58,
    approvers: 7,
    createdDaysAgo: 1,
    poster: "CodeMaster",
    posterHandle: "codemaster",
    verified: true,
    rating: 4.7,
    ratingCount: 289,
    successRate: 92,
    mode: "paid",
  },
  {
    id: "c4",
    title: "Street Daily — IG Followers",
    platform: "Instagram",
    action: "Follow",
    target: "@streetwear.daily",
    reward: 45,
    quantity: 400,
    budget: 20000,
    spent: 14040,
    status: "paused",
    completions: 312,
    approvers: 24,
    createdDaysAgo: 8,
    poster: "Street Daily",
    posterHandle: "streetdaily",
    verified: false,
    rating: 4.3,
    ratingCount: 118,
    successRate: 88,
    mode: "paid",
  },
  {
    id: "c5",
    title: "Brand X — TikTok Views",
    platform: "TikTok",
    action: "View",
    target: "/@brand/v/882",
    reward: 20,
    quantity: 2000,
    budget: 45000,
    spent: 19600,
    status: "completed",
    completions: 980,
    approvers: 88,
    createdDaysAgo: 14,
    poster: "Brand X",
    posterHandle: "brandx",
    verified: false,
    rating: 4.2,
    ratingCount: 87,
    successRate: 86,
    mode: "paid",
  },
];

export const EARNER_LEADERBOARD: LeaderEntry[] = [
  { rank: 1, handle: "ariachen", name: "Aria Chen", points: 48230, tier: "Platinum", trend: "up", isPremium: true },
  { rank: 2, handle: "diegor", name: "Diego Rivera", points: 42110, tier: "Platinum", trend: "up" },
  { rank: 3, handle: "meitanaka", name: "Mei Tanaka", points: 39845, tier: "Gold", trend: "flat", isPremium: true },
  { rank: 4, handle: "jordanray", name: "Jordan Ray", points: 37290, tier: "Gold", trend: "up" },
  { rank: 5, handle: "you", name: "You", points: 34820, tier: "Gold", trend: "up", isYou: true },
  { rank: 6, handle: "sarakhan", name: "Sara Khan", points: 33410, tier: "Gold", trend: "down", isPremium: true },
  { rank: 7, handle: "pabloo", name: "Pablo Ortiz", points: 31280, tier: "Gold", trend: "up" },
  { rank: 8, handle: "linwu", name: "Lin Wu", points: 28950, tier: "Silver", trend: "flat" },
  { rank: 9, handle: "evemu", name: "Eve Müller", points: 26110, tier: "Silver", trend: "down" },
  { rank: 10, handle: "kenadams", name: "Ken Adams", points: 23440, tier: "Silver", trend: "up" },
];

export const PROMOTER_LEADERBOARD: LeaderEntry[] = [
  { rank: 1, handle: "luxewears", name: "Luxe Wears", points: 124000, tier: "Platinum", trend: "up", isPremium: true },
  { rank: 2, handle: "cryptoalpha", name: "CryptoAlpha", points: 98500, tier: "Platinum", trend: "up", isPremium: true },
  { rank: 3, handle: "you", name: "You", points: 71200, tier: "Platinum", trend: "up", isYou: true },
  { rank: 4, handle: "web3wave", name: "Web3Wave", points: 68900, tier: "Platinum", trend: "down", isPremium: true },
  { rank: 5, handle: "codemaster", name: "CodeMaster", points: 53000, tier: "Gold", trend: "up", isPremium: true },
  { rank: 6, handle: "nftdrops", name: "NFTDropsHub", points: 49500, tier: "Gold", trend: "flat", isPremium: true },
  { rank: 7, handle: "streetdaily", name: "Street Daily", points: 41200, tier: "Gold", trend: "up" },
  { rank: 8, handle: "brandx", name: "Brand X", points: 38400, tier: "Gold", trend: "down" },
];

export const TRANSACTIONS: Transaction[] = [
  { id: "tx1", type: "earn", label: "Follow @luxewears (Instagram)", amount: 50, date: "Today, 2:14 PM", meta: "Task #t1" },
  { id: "tx2", type: "earn", label: "Join @CryptoAlphaVIP (Telegram)", amount: 80, date: "Today, 11:30 AM", meta: "Task #t2" },
  { id: "tx3", type: "spend", label: "Escrow deposited: CodeMaster subs", amount: -36000, date: "Yesterday, 6:02 PM", meta: "Campaign #c3" },
  { id: "tx4", type: "earn", label: "Like TikTok video", amount: 20, date: "Yesterday, 4:48 PM" },
  { id: "tx5", type: "reject", label: "Rejected claim - screenshot invalid", amount: -25, date: "Yesterday, 11:11 AM", meta: "Penalty" },
  { id: "tx6", type: "referral", label: "Referral bonus: @mike.eth", amount: 0.49, date: "2 days ago" },
  { id: "tx7", type: "deposit", label: "USDT deposit (NOWPayments)", amount: 100, date: "2 days ago", meta: "TRX" },
  { id: "tx8", type: "premium", label: "Premium membership — 1 Month", amount: -1.99, date: "5 days ago" },
  { id: "tx9", type: "earn", label: "Retweet @PromoPulse", amount: 40, date: "3 days ago" },
];

export const SEED_SUBMISSIONS: Submission[] = [
  // Claims submitted to YOUR ads (reviewable on /campaigns)
  { id: "cl1", userId: "mike.eth", handle: "mike.eth", name: "Mike Eth", platform: "Instagram", target: "@you", action: "Follow", reward: 45, submittedAt: "2 minutes ago", status: "pending", proof: "proof_8121.jpg", poster: "You", posterHandle: "you" },
  { id: "cl2", userId: "lin_wu", handle: "linwu", name: "Lin Wu", platform: "Instagram", target: "@you", action: "Follow", reward: 45, submittedAt: "7 minutes ago", status: "pending", proof: "proof_8122.png", poster: "You", posterHandle: "you" },
  { id: "cl3", userId: "sarakhan", handle: "sarakhan", name: "Sara Khan", platform: "Telegram", target: "@you", action: "Join", reward: 60, submittedAt: "14 minutes ago", status: "pending", proof: "proof_8123.jpg", poster: "You", posterHandle: "you" },
  { id: "cl4", userId: "pabloo", handle: "pabloo", name: "Pablo Ortiz", platform: "Twitter", target: "@you", action: "Retweet", reward: 35, submittedAt: "23 minutes ago", status: "pending", proof: "proof_8124.png", poster: "You", posterHandle: "you" },
  // Your own submissions (with statuses)
  { id: "my1", userId: "you", handle: "you", name: "You", platform: "Instagram", target: "@luxewears", action: "Follow", reward: 50, submittedAt: "3 hours ago", status: "approved", proof: "my_proof_10.png", poster: "Luxe Wears", posterHandle: "luxewears" },
  { id: "my2", userId: "you", handle: "you", name: "You", platform: "YouTube", target: "@CodeMasterPro", action: "Subscribe", reward: 120, submittedAt: "Yesterday", status: "rejected", reason: "Screenshot is not from the account @CodeMasterPro — please retake it showing the subscribed channel.", proof: "my_proof_09.png", poster: "CodeMaster", posterHandle: "codemaster" },
  { id: "my3", userId: "you", handle: "you", name: "You", platform: "Telegram", target: "@CryptoAlphaVIP", action: "Join", reward: 80, submittedAt: "Yesterday, 8:12 PM", status: "pending", proof: "my_proof_11.jpg", poster: "CryptoAlpha", posterHandle: "cryptoalpha" },
  // Leaderboard users' submissions (shown on /users/[handle])
  { id: "ar1", userId: "ariachen", handle: "ariachen", name: "Aria Chen", platform: "Instagram", target: "@luxewears", action: "Follow", reward: 50, submittedAt: "12 minutes ago", status: "approved", proof: "ar_8821.png", poster: "Luxe Wears", posterHandle: "luxewears" },
  { id: "ar2", userId: "ariachen", handle: "ariachen", name: "Aria Chen", platform: "Telegram", target: "@CryptoAlphaVIP", action: "Join", reward: 80, submittedAt: "1 hour ago", status: "pending", proof: "ar_8822.png", poster: "CryptoAlpha", posterHandle: "cryptoalpha" },
  { id: "ar3", userId: "ariachen", handle: "ariachen", name: "Aria Chen", platform: "YouTube", target: "@CodeMasterPro", action: "Subscribe", reward: 120, submittedAt: "4 hours ago", status: "rejected", reason: "Channel not subscribed — subscription was removed before review.", proof: "ar_8819.png", poster: "CodeMaster", posterHandle: "codemaster" },
  { id: "dg1", userId: "diegor", handle: "diegor", name: "Diego Rivera", platform: "Twitter", target: "@PromoPulse/status/1729", action: "Retweet", reward: 40, submittedAt: "26 minutes ago", status: "approved", proof: "dg_7721.png", poster: "PromoPulse", posterHandle: "promopulse" },
  { id: "dg2", userId: "diegor", handle: "diegor", name: "Diego Rivera", platform: "TikTok", target: "/@brand/v/882", action: "View", reward: 20, submittedAt: "2 hours ago", status: "pending", proof: "dg_7722.jpg", poster: "Brand X", posterHandle: "brandx" },
  { id: "mt1", userId: "meitanaka", handle: "meitanaka", name: "Mei Tanaka", platform: "Telegram", target: "@CryptoAlphaVIP", action: "Join", reward: 80, submittedAt: "40 minutes ago", status: "approved", proof: "mt_4412.png", poster: "CryptoAlpha", posterHandle: "cryptoalpha" },
  { id: "mt2", userId: "meitanaka", handle: "meitanaka", name: "Mei Tanaka", platform: "Instagram", target: "@luxewears", action: "Follow", reward: 50, submittedAt: "3 hours ago", status: "rejected", reason: "Follow was removed within 7 days — anti-unfollow policy.", proof: "mt_4410.png", poster: "Luxe Wears", posterHandle: "luxewears" },
  { id: "jr1", userId: "jordanray", handle: "jordanray", name: "Jordan Ray", platform: "YouTube", target: "@CodeMasterPro", action: "Subscribe", reward: 120, submittedAt: "55 minutes ago", status: "pending", proof: "jr_9920.png", poster: "CodeMaster", posterHandle: "codemaster" },
  { id: "jr2", userId: "jordanray", handle: "jordanray", name: "Jordan Ray", platform: "Twitter", target: "@Web3Wave", action: "Follow", reward: 60, submittedAt: "5 hours ago", status: "rejected", reason: "Account does not follow @Web3Wave at review time.", proof: "jr_9915.png", poster: "Web3Wave", posterHandle: "web3wave" },
  { id: "sk1", userId: "sarakhan", handle: "sarakhan", name: "Sara Khan", platform: "Instagram", target: "@luxewears", action: "Follow", reward: 50, submittedAt: "1 hour ago", status: "approved", proof: "sk_2218.png", poster: "Luxe Wears", posterHandle: "luxewears" },
  { id: "sk2", userId: "sarakhan", handle: "sarakhan", name: "Sara Khan", platform: "TikTok", target: "/@brand/v/882", action: "View", reward: 20, submittedAt: "6 hours ago", status: "pending", proof: "sk_2212.jpg", poster: "Brand X", posterHandle: "brandx" },
  { id: "po1", userId: "pabloo", handle: "pabloo", name: "Pablo Ortiz", platform: "Telegram", target: "@CryptoAlphaVIP", action: "Join", reward: 80, submittedAt: "2 hours ago", status: "approved", proof: "po_6611.png", poster: "CryptoAlpha", posterHandle: "cryptoalpha" },
  { id: "lw1", userId: "linwu", handle: "linwu", name: "Lin Wu", platform: "Instagram", target: "@streetwear.daily", action: "Follow", reward: 45, submittedAt: "3 hours ago", status: "pending", proof: "lw_3301.png", poster: "Street Daily", posterHandle: "streetdaily" },
  { id: "ev1", userId: "evemu", handle: "evemu", name: "Eve Müller", platform: "YouTube", target: "@CodeMasterPro", action: "Like", reward: 15, submittedAt: "7 hours ago", status: "rejected", reason: "Like was not present on the video during verification.", proof: "ev_1144.png", poster: "CodeMaster", posterHandle: "codemaster" },
  { id: "ka1", userId: "kenadams", handle: "kenadams", name: "Ken Adams", platform: "Twitter", target: "@Web3Wave", action: "Follow", reward: 60, submittedAt: "4 hours ago", status: "pending", proof: "ka_7788.png", poster: "Web3Wave", posterHandle: "web3wave" },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  { id: "n1", type: "follow", title: "Aria Chen followed you", description: "You gained a new follower", at: "5 minutes ago", read: false },
  { id: "n2", type: "new_ad", title: "@luxewears posted a new ad", description: "Follow @luxewears for daily drops · +$50", at: "1 hour ago", read: false },
  { id: "n3", type: "claim", title: "Claim approved", description: "Your submission for Follow @luxewears was approved · +$50", at: "3 hours ago", read: false },
  { id: "n4", type: "claim", title: "Claim rejected", description: "Subscribe @CodeMasterPro — Screenshot is not from the correct account", at: "Yesterday", read: true },
  { id: "n5", type: "system", title: "Welcome to PromoPulse", description: "Complete 6 referrals to unlock withdrawals", at: "3 days ago", read: true },
];

/** Referral milestones (USDT). */
export const REFERRAL_MILESTONES = [
  { count: 1, label: "1 refer", reward: "+$0.49 per refer" },
  { count: 6, label: "6 refers", reward: "Withdrawal unlocked" },
  { count: 7, label: "7 refers", reward: "+$5.00 extra" },
  { count: 10, label: "10 refers", reward: "Premium · 1 week" },
];
